ALTER TABLE `user`
  ADD COLUMN `store_name` VARCHAR(100) NULL DEFAULT NULL,
  ADD COLUMN `store_description` VARCHAR(250) NULL DEFAULT NULL,
  ADD COLUMN `store_url` VARCHAR(255) UNIQUE NULL DEFAULT NULL,
  ADD COLUMN `store_logo` VARCHAR(255) NULL DEFAULT NULL;
